package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"gowebtemplate/src/server/db/ent/codegen"
	graphql1 "gowebtemplate/src/server/graphql/generated"
	"gowebtemplate/src/server/graphql/models"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input *codegen.CreateTodoInput) (*codegen.Todo, error) {
	entInput := codegen.CreateTodoInput{
		Text:     input.Text,
		Complete: input.Complete,
		UserID:   input.UserID,
	}
	return r.Ent.Todo.Create().SetInput(entInput).Save(ctx)
}

// Foo is the resolver for the foo field.
func (r *queryResolver) Foo(ctx context.Context) (*models.Foo, error) {
	return nil, nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
